### PR TITLE
Publish Microsoft Authored templates to azure samples browser

### PR DESCRIPTION
**Pull request by jianingwang123**
Publish `function-python-ai-openai-chatgpt` template to azure samples browser.

@rajeshkamal5050 and @hemarina for notification.

### CODE REVIEW

**Review by hemarina — APPROVED** [review]
LGTM. @paulyuk for notification. Could you review this PR?

**Comment by v-xuto** [comment]
@paulyuk Could you help review this PR and merge it if it looks good?

**Comment by zedy-wj** [comment]
@paulyuk Could you help review this PR and merge it if it looks good?

**Review by paulyuk — APPROVED** [review]
LGTM

**Comment by paulyuk** [comment]
thank you for the contribution!

**Pull request merged**
